// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBEEQVotF6XBogxjo-vKAwNopQ2v5szOY',
    appId: '1:802427920595:web:1a0ff84ae9efe7ea453426',
    messagingSenderId: '802427920595',
    projectId: 'bmic-a0320',
    authDomain: 'bmic-a0320.firebaseapp.com',
    storageBucket: 'bmic-a0320.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjnW_8C7c9aiVai9vQ193TeEL28kAbH7Q',
    appId: '1:802427920595:android:a98162e7a18fc0aa453426',
    messagingSenderId: '802427920595',
    projectId: 'bmic-a0320',
    storageBucket: 'bmic-a0320.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmL5h6hXUt44bsCSCpwUZyMDNZ2ICfChw',
    appId: '1:802427920595:ios:4001ca3b3261d598453426',
    messagingSenderId: '802427920595',
    projectId: 'bmic-a0320',
    storageBucket: 'bmic-a0320.firebasestorage.app',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmL5h6hXUt44bsCSCpwUZyMDNZ2ICfChw',
    appId: '1:802427920595:ios:4001ca3b3261d598453426',
    messagingSenderId: '802427920595',
    projectId: 'bmic-a0320',
    storageBucket: 'bmic-a0320.firebasestorage.app',
    iosBundleId: 'com.example.bmi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBEEQVotF6XBogxjo-vKAwNopQ2v5szOY',
    appId: '1:802427920595:web:ab8fab53aaee26b1453426',
    messagingSenderId: '802427920595',
    projectId: 'bmic-a0320',
    authDomain: 'bmic-a0320.firebaseapp.com',
    storageBucket: 'bmic-a0320.firebasestorage.app',
  );
}
